image: regoo707/apps:$IMAGE_TAG
services:
  - docker:dind

stages:
  - test
  - build
  - deploy

test:
  stage: test
  script:
    - npm run build
    - npm run test

build:
  stage: build
  script:
    - docker login -u "regoo707" -p "P@ssw0rdroot77" docker.io
    - docker build --pull -t "regoo707/apps:$IMAGE_TAG" .
    - docker push "regoo707/apps:$IMAGE_TAG"
    - docker rmi "regoo707/apps:$IMAGE_TAG"

deploy:
  stage: deploy
  script:
    - ~/rancher login https://$RANCHER_URL/v3 --token $RANCHER_ACCESS_TOKEN --skip-verify
    - ~/rancher catalog refresh $RANCHER_CATELOG_NAME --wait
    - ~/rancher app upgrade $RANCHER_APP_NAME 0.1.5
